---
- hosts: localhost
  connection: local

  tasks:

    - name: local config template
      template: src=local.sys.config.j2 dest=local.sys.config
    - name: qa config template
      template: src=qa.sys.config.j2 dest=qa.sys.config
