---
- hosts: localhost
  connection: local

  tasks:

    - name: local config template
      template: src=local.sys.config.j2 dest=local.sys.config
    - name: qa config template
      template: src=qa.sys.config.j2 dest=qa.sys.config
    - name: run tar as qa
      shell: rebar3 as qa tar
      register: release
    - name: copy tar to server

- hosts: dog_trainer

  tasks:
      - name: 
        sudo mkdir dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08 
        cd dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08
        tar xf ~/dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08.tar.gz 
        sudo tar xf ~/dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08.tar.gz 
        cd ..
        ls -altr
        rm dog_trainer
        sudo rm dog_trainer
        sudo chown -R dog: dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08
        sudo ln -s dog_trainer-8764e079c211005797923caf7cc2c6f8b0d17f08 dog_trainer
        ls -latr
        sudo systemctl restart dog_trainer

